### ISSUE TITLE
Repeated CV

### ISSUE THREAD

**Issue by ck37** [ledell/cvAUC#1]
Have you considered supporting repeated cross-validation, to further reduce the impact of random variation in folds? Seems pretty trivial to implement but is a good practice. It is a commonly used feature of Max Kuhn's caret package.

**Comment by ledell** [comment]
Yeah, it would be good to add support for repeated CV.  Thanks for the suggestion.  I won't be able to look into this until after I finish my dissertation (~6 weeks), but if you need it sooner, feel free to take a stab at it.  I'm happy to accept PRs.

**Comment by antoniomolins** [comment]
Hi there! Thanks for the great work. I was also wondering whether you would be supporting repeated cv, it would be really helpful.

**Comment by darrylbobo** [comment]
@ledell 

Any plan to add this repeated CV feature? It would be very helpful.

**Comment by MassimilianoGrassiDataScience** [comment]
Hi! I see the thread inactive but I would like to ask a similar question about repeated cv. 

Is it (theoretically) correct to calculate CI for repeated cv (10 folds, 10 repetitions) with the `ci.cvAUC` fucntion,  just indicating the folds as 100 distinct folds?

Thanks you!

**Comment by ledell** [comment]
@MassimilianoGrassiDataScience @antoniomolins @ck37 I have an answer for you about this (someone emailed me the same question and Mark van der Laan replied):

From Mark:

> Doing once V fold or 10 times V fold results in two estimators of AUC that are in first order identical, so that the influence curves are the same. So you will not get a reduced size of the CI  based on this influence curve based confidence interval. There is a paper Dudoit van der Laan Annals of stat 2006 or so, where we show that V fold is first order optimal and doing additional splits is not helping in first order. So my take would be to still use the same confidence interval but still have the benefit of having a more precise estimator of the AUC. 

Follow-up notes on this by me (using 10-fold, 10 repetition example):

Mark is suggesting is to use only one of the 10-fold repetitions to calculate the confidence intervals, however you can average the 10 CV AUC values to get a better estimate of AUC.  This is related to the theory behind how influence function based CIs are constructed. 

The `ci.cvAUC()` function computes the length of the CI and then returns the appropriate [min, max] value, centered at the CV AUC (also computed by the function).  If you want use the CV AUC value which is averaged over the 10 reps as the center of your CI rather than just the CV AUC for one repetition, then you should create a new `predictions` object which has the average values for each row (over the 10 reps).  Then if you pass that `predictions` object to `ci.cvAUC()`, along with the response, `Y`, and one set of 10 reps of folds, it will return a CI that’s properly centered around the avg CV AUC value (across 10 reps).  

Alternatively you can just use one of the repetitions, since the CIs would be the same.

**Comment by ck37** [comment]
Hi @ledell,

That is helpful and interesting analysis, thanks for sharing! That makes sense that repeated CV will not narrow the confidence interval.  (And this thread is a blast from the past - when I was taking Causal 1.)

Another aspect of repeated CV is that it seems like it would provide the metalearner with additional sample size to estimate the weights or otherwise fit the stacked data. So I have been wondering if it could lead to an increased AUC for the SuperLearner itself, reduce overfitting due to weight estimation, and might lower the chance that the SL estimator has slightly worse performance point estimates than the best non-ensemble algorithm(s) (even though it would usually be a statistical tie when CIs are examined). Maybe someone has tried it and gotten some empirical results? Although it's rare for ensembling software to support repeated CV.

But yeah this extra discussion is very helpful to see that the confidence interval estimation doesn't need to use the extra information in the repeats, which probably makes it unnecessary to consider as a feature for this package.

Cheers,
Chris
